"""followers

Revision ID: 134c23538158
Revises: 2a1e1d069ccf
Create Date: 2022-08-31 11:33:34.296803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134c23538158'
down_revision = '2a1e1d069ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Folowers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Folowers')
    # ### end Alembic commands ###
